services:
  data-loading-webapp:
    develop:
      watch:
        - action: sync+restart
          path: ./edge-vm/webapp
          target: /app/webapp
        - action: sync
          path: ./edge-vm/webapp/templates
          target: /app/webapp/templates
        - action: rebuild
          path: ./edge-vm/requirements.txt

  trino:
    depends_on: !reset []

  cdc-script:
    depends_on: !override
      trino:
        condition: service_healthy
      kafka-init:
        condition: service_completed_successfully