services:
# ----------------------------- FILE WATCHER -----------------------------
  data-loading-webapp:
    profiles:
      - without-visualization
      - complete

# ----------------------------- KAFKA -----------------------------
  kafka-broker-0:
    profiles:
      - without-visualization
      - complete

  # kafka-broker-1:
  #   profiles:
  #     - without-visualization
  #     - complete

  kafka-init:
    profiles:
      - without-visualization
      - complete

# ----------------------------- HIVE METASTORE -----------------------------
  hive-metastore:
    profiles:
      - without-visualization
      - complete

# ----------------------------- MINIO -----------------------------
  minio:
    profiles:
      - without-visualization
      - complete

  minio-init:
    profiles:
      - without-visualization
      - complete

# ----------------------------- TRINO -----------------------------
  trino:
    profiles:
      - without-visualization
      - complete

# ----------------------------- CDC -----------------------------
  cdc-script:
    profiles:
      - without-visualization
      - complete

# ----------------------------- RANGER -----------------------------
  ranger:
    profiles:
      - without-visualization
      - complete

  ranger-zk:
    profiles:
      - without-visualization
      - complete

  ranger-solr:
    profiles:
      - without-visualization
      - complete

  ranger-db:
    profiles:
      - without-visualization
      - complete

  # ranger-tagsync:
  #   profiles:
  #     - without-visualization
  #     - complete

# ----------------------------- ATLAS  -----------------------------

  atlas:
    profiles:
      - without-visualization
      - complete

# ----------------------------- HUE -----------------------------
  # hue:
  #   profiles:
  #     - complete

# ----------------------------- SUPERSET -----------------------------
  superset:
    profiles:
      - complete
