services:
  data-loading-webapp:
    develop:
      develop:
      watch:
        - action: sync+restart
          path: ./webapp
          target: /app/webapp
        - action: rebuild
          path: ./remote_machine/requirements.txt