services:
  data-loading-webapp:
    develop:
      watch:
        - action: sync+restart
          path: ./edge-vm/webapp
          target: /app/webapp
        - action: rebuild
          path: ./edge-vm/requirements.txt