services:
  user-dashboard:
    environment:
      - FLASK_TEMPLATES_AUTO_RELOAD=True
    develop:
      watch:
        - action: sync+restart
          path: ./edge-vm/webapp
          target: /app/webapp
          ignore:
            - templates/
            - static/
        - action: sync
          path: ./edge-vm/webapp/templates
          target: /app/webapp/templates
        - action: sync
          path: ./edge-vm/webapp/static
          target: /app/webapp/static
        - action: rebuild
          path: ./edge-vm/requirements.txt

  trino:
    depends_on: !reset []

  cdc-script:
    depends_on: !override
      trino:
        condition: service_healthy
      kafka-init:
        condition: service_completed_successfully

  task-results-handler:
    develop:
      watch:
        - action: sync+restart
          path: ./task-results-handler/api
          target: /app/api
        - action: rebuild
          path: ./task-results-handler/requirements.txt