services:
# ----------------------------- FILE WATCHER -----------------------------
  watcher:
    profiles:
      - minimal

# ----------------------------- KAFKA -----------------------------
  kafka-broker-0:
    profiles:
      - ranger-test
      - minimal

  # kafka-broker-1:
  #   profiles:
  #     - ranger-test

  kafka-init:
    profiles:
      - ranger-test
      - minimal

# ----------------------------- HIVE METASTORE -----------------------------
  hive-metastore:
    profiles: []

# ----------------------------- MINIO -----------------------------
  minio:
    profiles: []

  minio-init:
    profiles: []

# ----------------------------- TRINO -----------------------------
  trino:
    profiles:
      - ranger-test
      - sql-ui
      - minimal

# ----------------------------- CDC -----------------------------
  cdc-script:
    profiles: []

# ----------------------------- HUE -----------------------------
  hue:
    profiles:
      - sql-ui

# ----------------------------- RANGER -----------------------------
  ranger:
    profiles:
      - ranger-test
      - sql-ui
      - minimal

  ranger-zk:
    profiles:
      - ranger-test
      - sql-ui
      - minimal

  ranger-solr:
    profiles:
      - ranger-test
      - sql-ui
      - minimal

  ranger-db:
    profiles:
      - ranger-test
      - sql-ui
      - minimal