apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kafka-svc
{{ $metaInfo := dict "PartOf" "kafka" "Component" "svc" "Global" . -}}
{{ include "prin.commonMetadata" $metaInfo | indent 2 }}
spec:
  ports:
    - port: 9092
      targetPort: listening
      name: listening
    - port: 9093
      targetPort: control-plane
      name: control-plane
  type: ClusterIP
  clusterIP: None
  selector:
{{ include "prin.commonLabels" ( dict "PartOf" "kafka" "Component" "node" "Global" . ) | indent 4 }}
