apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-minio-secret
{{ $metaInfo := dict "PartOf" "minio" "Component" "secret" "Global" . -}}
{{ include "prin.commonMetadata" $metaInfo | indent 2 }}
type: Opaque
data:
  # MINIO_ROOT_USER: miniouser
  MINIO_ROOT_USER: bWluaW91c2Vy
  # MINIO_ROOT_PASSWORD: miniopassword
  MINIO_ROOT_PASSWORD: bWluaW9wYXNzd29yZA==
