apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-webapp-deployment
{{ $metaInfo := dict "PartOf" "webapp" "Component" "node" "Global" . -}}
{{ include "prin.commonMetadata" $metaInfo | indent 2 -}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/part-of: "webapp"
      app.kubernetes.io/component: "node"
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: "webapp"
        app.kubernetes.io/component: "node"
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80